spring:
  data:
    mongodb:
      uri: mongodb+srv://beggars:N6D8uhjyyQ5oUgSR@dba-cluster.wog0o99.mongodb.net/
      database: MetroSystemPAWA
server:
  port: 8080

# JWT configuration
jwt:
  secret: "i5q9Y0k2QzV4T3V5Q2p4V0s1bWs3R2l3c2Z4bW4xazg="
  expiration: 3600


logging:
  level:
    org.springframework.security: DEBUG
